### ISSUE TITLE
Remove Compiled Assets

### ISSUE THREAD

**Issue by 0xcaff** [uofw/uofwinst#1]
There are many compiled assets in this repository:
- `dist/`

Committing compiled assets is a bad idea because it puts unnecessary load on github's servers and slows down transfer speeds. Let's move these binaries to the `gh-pages` branch and link to them like: `uofw.github.io/uofwinst/dist`

**Comment by artart78** [comment]
I just removed them, maybe we could find somewhere to put them later, but it's not that important right now since anybody with the PSP toolchain should be able to build it.
